@host = https://localhost:7196

### Registrar usuario
POST {{host}}/api/usuario/registrar
Content-Type: application/json

{
  "nombreCompleto": "Juan Pérez",
  "correo": "juan@test.com",
  "password": "123456",
  "telefono": "999888777"
}

### Login
POST {{host}}/api/usuario/login
Content-Type: application/json

{
  "correo": "juan@test.com",
  "password": "123456"
}

### Listar usuarios
GET {{host}}/api/usuario